In [1]:
# Supply Chain & Demand Analysis — Food Manufacturing Context
# Author: Eric Lindolfo, B.Eng
# Notebook 01: Data Exploration

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:
# Loading Grocery Inventory Dataset
# Source: Kaggle — Grocery Inventory by Willian Oliveira
# Goal: Understand inventory structure for expiry risk and supplier analysis
# .read_csv() → reads the CSV file and stores it as a DataFrame (table)

inventory = pd.read_csv('data/Grocery_Inventory_new_v1.csv')

# .shape → shows (number of rows, number of columns)
print("Shape:", inventory.shape)

# .columns → lists all column names
print("\nColumns:", inventory.columns.tolist())

Shape: (990, 17)

Columns: ['Product_Name', 'Catagory', 'Supplier_Name', 'Warehouse_Location', 'Status', 'Product_ID', 'Supplier_ID', 'Date_Received', 'Last_Order_Date', 'Expiration_Date', 'Stock_Quantity', 'Reorder_Level', 'Reorder_Quantity', 'Unit_Price', 'Sales_Volume', 'Inventory_Turnover_Rate', 'percentage']

In [3]:
# .head() → shows first 5 rows of the dataset
# Goal: visually inspect the data structure

inventory.head()

,Product_Name,Catagory,Supplier_Name,Warehouse_Location,Status,Product_ID,Supplier_ID,Date_Received,Last_Order_Date,Expiration_Date,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Sales_Volume,Inventory_Turnover_Rate,percentage
0,Bell Pepper,Fruits & Vegetables,Eimbee,20 Pennsylvania Parkway,Discontinued,29-017-6255,43-348-2450,3/1/2024,1/6/2025,1/31/2025,46,64,17,$4.60,96,55,1.96%
1,Vegetable Oil,Oils & Fats,Digitube,03643 Oakridge Lane,Backordered,79-569-8856,04-854-7165,4/1/2024,5/19/2024,6/11/2024,51,87,86,$2.00,24,83,0.91%
2,Parmesan Cheese,Dairy,BlogXS,73 Graedel Street,Discontinued,28-146-2641,82-995-0739,4/1/2024,12/21/2024,4/8/2024,38,67,66,$12.00,35,24,1.36%
3,Carrot,Fruits & Vegetables,Avaveo,44801 Myrtle Center,Discontinued,11-581-9869,22-867-3079,5/1/2024,12/12/2024,9/26/2024,51,60,98,$1.50,44,95,1.36%
4,Garlic,Fruits & Vegetables,Katz,6195 Monterey Center,Discontinued,13-202-4809,24-281-7685,5/1/2024,7/28/2024,5/20/2024,27,22,89,$7.00,91,77,2.17%

In [4]:
# .info() → shows column types and missing values
# Goal: identify data types and null values before cleaning

inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product_Name             990 non-null    object
 1   Catagory                 989 non-null    object
 2   Supplier_Name            990 non-null    object
 3   Warehouse_Location       990 non-null    object
 4   Status                   990 non-null    object
 5   Product_ID               990 non-null    object
 6   Supplier_ID              990 non-null    object
 7   Date_Received            990 non-null    object
 8   Last_Order_Date          990 non-null    object
 9   Expiration_Date          990 non-null    object
 10  Stock_Quantity           990 non-null    int64
 11  Reorder_Level            990 non-null    int64
 12  Reorder_Quantity         990 non-null    int64
 13  Unit_Price               990 non-null    object
 14  Sales_Volume             990 non-null    int64
 15  Inventory_Turnover_Rate  990 non-null    int64
 16  percentage               990 non-null    object
dtypes: int64(5), object(12)
memory usage: 131.6+ KB

In [5]:
# .describe() → shows statistical summary of numerical columns
# Goal: understand ranges, averages, and spot anomalies

inventory.describe()

,Stock_Quantity,Reorder_Level,Reorder_Quantity,Sales_Volume,Inventory_Turnover_Rate
count,990.000000,990.000000,990.000000,990.000000,990.000000
mean,55.609091,51.215152,51.913131,58.925253,50.150505
std,26.300775,29.095241,29.521059,23.002318,28.798954
min,10.000000,1.000000,1.000000,20.000000,1.000000
25%,33.000000,25.250000,25.000000,39.000000,25.000000
50%,56.000000,53.000000,54.000000,58.000000,50.000000
75%,79.000000,77.000000,77.000000,78.000000,74.750000
max,100.000000,100.000000,100.000000,100.000000,100.000000